// Generated by .codex-tmp/build_destination_intelligence.js on 2026-05-28.

export const destinationProfiles = [
  {
    "destinationId": "paris",
    "destination": "Paris",
    "aliases": [
      "Paris, France"
    ],
    "country": "France",
    "currency": "EUR",
    "clusters": [
      {
        "id": "paris_seine_core",
        "label": "Seine Icons",
        "routeZone": "central",
        "planningMeaning": "Eiffel Tower, river monuments, museums, and high-crowd first-time Paris anchors."
      },
      {
        "id": "paris_left_bank",
        "label": "Left Bank",
        "routeZone": "left_bank",
        "planningMeaning": "Museums, gardens, cafes, literary walks, and slower culture blocks."
      },
      {
        "id": "paris_north_villages",
        "label": "Montmartre and North Paris",
        "routeZone": "north",
        "planningMeaning": "Village hills, viewpoints, nightlife edges, and photography-heavy walking."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/800px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg",
      "source": "wikipedia",
      "pageTitle": "Paris",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "tokyo",
    "destination": "Tokyo",
    "aliases": [
      "Tokyo, Japan"
    ],
    "country": "Japan",
    "currency": "JPY",
    "clusters": [
      {
        "id": "tokyo_east_old_tokyo",
        "label": "Asakusa and East Tokyo",
        "routeZone": "east",
        "planningMeaning": "Temples, river walks, traditional streets, and skyline transitions."
      },
      {
        "id": "tokyo_west_youth_city",
        "label": "Shibuya, Shinjuku, and Harajuku",
        "routeZone": "west",
        "planningMeaning": "Neon, youth culture, parks, nightlife, and high-energy walking."
      },
      {
        "id": "tokyo_bay_modern",
        "label": "Toyosu and Tokyo Bay",
        "routeZone": "bay",
        "planningMeaning": "Digital art, food markets, islands, and futuristic indoor backups."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/800px-Skyscrapers_of_Shinjuku_2009_January.jpg",
      "source": "wikipedia",
      "pageTitle": "Tokyo",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "rome",
    "destination": "Rome",
    "aliases": [
      "Rome, Italy"
    ],
    "country": "Italy",
    "currency": "EUR",
    "clusters": [
      {
        "id": "rome_ancient_core",
        "label": "Ancient Core",
        "routeZone": "ancient",
        "planningMeaning": "Colosseum, Forum, Pantheon, and dense walking-heavy heritage."
      },
      {
        "id": "rome_vatican_prati",
        "label": "Vatican and Prati",
        "routeZone": "west",
        "planningMeaning": "Museums, basilicas, river crossings, and reservation-sensitive anchors."
      },
      {
        "id": "rome_trastevere_centro",
        "label": "Trastevere and Centro",
        "routeZone": "central",
        "planningMeaning": "Food lanes, piazzas, fountains, and low-friction evening flow."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Trevi_Fountain%2C_Rome%2C_Italy_2_-_May_2007.jpg/800px-Trevi_Fountain%2C_Rome%2C_Italy_2_-_May_2007.jpg",
      "source": "wikipedia",
      "pageTitle": "Rome",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "bali",
    "destination": "Bali",
    "aliases": [
      "Bali, Indonesia"
    ],
    "country": "Indonesia",
    "currency": "IDR",
    "clusters": [
      {
        "id": "bali_ubud_central",
        "label": "Ubud Culture and Rice Terraces",
        "routeZone": "ubud",
        "planningMeaning": "Temples, craft villages, rice terraces, cafes, and wellness blocks."
      },
      {
        "id": "bali_south_coast",
        "label": "South Bali Coast",
        "routeZone": "south",
        "planningMeaning": "Beaches, surf towns, cliff temples, sunset dinners, and nightlife."
      },
      {
        "id": "bali_island_daytrips",
        "label": "Island and Volcano Day Trips",
        "routeZone": "outer",
        "planningMeaning": "Nusa Penida, Mount Batur, and long-transfer adventure days."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Bali_in_Indonesia_%28special_marker%29.svg/800px-Bali_in_Indonesia_%28special_marker%29.svg.png",
      "source": "wikipedia",
      "pageTitle": "Bali",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "maldives",
    "destination": "Maldives",
    "aliases": [
      "Maldives"
    ],
    "country": "Maldives",
    "currency": "MVR",
    "clusters": [
      {
        "id": "maldives_male_hulhumale",
        "label": "Malé and Hulhumalé",
        "routeZone": "urban",
        "planningMeaning": "Arrival buffers, local markets, ferries, and airport-safe planning."
      },
      {
        "id": "maldives_local_islands",
        "label": "Local Islands",
        "routeZone": "islands",
        "planningMeaning": "Maafushi, Fulidhoo, Dhigurah, guesthouses, sandbanks, and budget reef access."
      },
      {
        "id": "maldives_resort_reef",
        "label": "Resort and Reef Escapes",
        "routeZone": "reef",
        "planningMeaning": "Premium resorts, manta zones, bioluminescence, and boat-dependent anchors."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/800px-Flag_of_Maldives.svg.png",
      "source": "wikipedia",
      "pageTitle": "Maldives",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "new_york_city",
    "destination": "New York City",
    "aliases": [
      "New York",
      "NYC",
      "New York City, USA"
    ],
    "country": "USA",
    "currency": "USD",
    "clusters": [
      {
        "id": "new_york_city_midtown_icons",
        "label": "Midtown Icons",
        "routeZone": "midtown",
        "planningMeaning": "Skyscraper views, Times Square, major museums, and high-density tourist anchors."
      },
      {
        "id": "new_york_city_downtown_waterfront",
        "label": "Downtown and Waterfront",
        "routeZone": "downtown",
        "planningMeaning": "Harbor, bridges, history, walks, and skyline transitions."
      },
      {
        "id": "new_york_city_west_village_brooklyn",
        "label": "Village, Chelsea, and Brooklyn",
        "routeZone": "west",
        "planningMeaning": "Food, parks, neighborhoods, galleries, and social evening flow."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/800px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg",
      "source": "wikipedia",
      "pageTitle": "New York City",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "dubai",
    "destination": "Dubai",
    "aliases": [
      "Dubai, UAE"
    ],
    "country": "UAE",
    "currency": "AED",
    "clusters": [
      {
        "id": "dubai_downtown_dubai",
        "label": "Downtown Dubai",
        "routeZone": "downtown",
        "planningMeaning": "Burj Khalifa, malls, fountains, museums, and polished indoor comfort."
      },
      {
        "id": "dubai_old_dubai_creek",
        "label": "Old Dubai and Creek",
        "routeZone": "creek",
        "planningMeaning": "Souks, abras, heritage lanes, mosques, and cultural contrast."
      },
      {
        "id": "dubai_coast_desert",
        "label": "Coast, Palm, and Desert",
        "routeZone": "outer",
        "planningMeaning": "Beach clubs, Palm landmarks, desert conservation, and high-luxury escapes."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Burj_Khalifa_2021.jpg/800px-Burj_Khalifa_2021.jpg",
      "source": "wikipedia",
      "pageTitle": "Dubai",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "barcelona",
    "destination": "Barcelona",
    "aliases": [
      "Barcelona, Spain"
    ],
    "country": "Spain",
    "currency": "EUR",
    "clusters": [
      {
        "id": "barcelona_gaudi_core",
        "label": "Gaudí Core",
        "routeZone": "eixample",
        "planningMeaning": "Sagrada Família, Casa Batlló, Park Güell, and reservation-heavy architecture."
      },
      {
        "id": "barcelona_old_city_gothic",
        "label": "Gothic and Born",
        "routeZone": "old_city",
        "planningMeaning": "Medieval lanes, markets, tapas, museums, and compact walking."
      },
      {
        "id": "barcelona_coast_montjuic",
        "label": "Coast and Montjuïc",
        "routeZone": "coast",
        "planningMeaning": "Beach, viewpoints, parks, and evening recovery."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Aerial_view_of_Barcelona%2C_Spain_%2851227309370%29_edited.jpg/800px-Aerial_view_of_Barcelona%2C_Spain_%2851227309370%29_edited.jpg",
      "source": "wikipedia",
      "pageTitle": "Barcelona",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "cape_town",
    "destination": "Cape Town",
    "aliases": [
      "Cape Town, South Africa"
    ],
    "country": "South Africa",
    "currency": "ZAR",
    "clusters": [
      {
        "id": "cape_town_city_bowl",
        "label": "City Bowl",
        "routeZone": "central",
        "planningMeaning": "Table Mountain, Bo-Kaap, museums, food streets, and weather-sensitive views."
      },
      {
        "id": "cape_town_waterfront_atlantic",
        "label": "Waterfront and Atlantic Coast",
        "routeZone": "coast",
        "planningMeaning": "V&A, Robben Island, beaches, sunsets, and easy social flow."
      },
      {
        "id": "cape_town_peninsula_gardens",
        "label": "Peninsula and Gardens",
        "routeZone": "outer",
        "planningMeaning": "Kirstenbosch, Cape Point, penguins, and longer scenic routes."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Camps_bay_%2853460319478%29_%28cropped%29.jpg/800px-Camps_bay_%2853460319478%29_%28cropped%29.jpg",
      "source": "wikipedia",
      "pageTitle": "Cape Town",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "great_barrier_reef",
    "destination": "Great Barrier Reef",
    "aliases": [
      "Great Barrier Reef, Australia",
      "Cairns"
    ],
    "country": "Australia",
    "currency": "AUD",
    "clusters": [
      {
        "id": "great_barrier_reef_cairns_base",
        "label": "Cairns Base",
        "routeZone": "cairns",
        "planningMeaning": "Arrival, reef departures, lagoon recovery, and low-friction food."
      },
      {
        "id": "great_barrier_reef_reef_islands",
        "label": "Reef Islands",
        "routeZone": "reef",
        "planningMeaning": "Green Island, Fitzroy, outer reef pontoons, and boat-day planning."
      },
      {
        "id": "great_barrier_reef_rainforest_coast",
        "label": "Rainforest Coast",
        "routeZone": "north",
        "planningMeaning": "Daintree, Port Douglas, Whitsundays-style add-ons, and long nature transfers."
      }
    ],
    "heroImage": {
      "url": "https://staticmap.openstreetmap.de/staticmap.php?center=-16.9186,145.7781&zoom=14&size=800x600&markers=-16.9186,145.7781,red-pushpin",
      "source": "place_fallback",
      "pageTitle": "Great Barrier Reef",
      "attribution": "Derived from first place image"
    },
    "replacementNote": null
  },
  {
    "destinationId": "amsterdam",
    "destination": "Amsterdam",
    "aliases": [
      "Amsterdam, Netherlands"
    ],
    "country": "Netherlands",
    "currency": "EUR",
    "clusters": [
      {
        "id": "amsterdam_museumplein",
        "label": "Museumplein",
        "routeZone": "south",
        "planningMeaning": "Art museums, park recovery, and reservation-heavy culture."
      },
      {
        "id": "amsterdam_canal_core",
        "label": "Canal Ring and Jordaan",
        "routeZone": "central",
        "planningMeaning": "Canals, history, cafes, compact walks, and crowd-sensitive icons."
      },
      {
        "id": "amsterdam_north_creative",
        "label": "Amsterdam North",
        "routeZone": "north",
        "planningMeaning": "Creative docks, ferries, street art, and lower-friction social blocks."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png/800px-Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png",
      "source": "wikipedia",
      "pageTitle": "Amsterdam",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "istanbul",
    "destination": "Istanbul",
    "aliases": [
      "Istanbul, Turkey"
    ],
    "country": "Turkey",
    "currency": "TRY",
    "clusters": [
      {
        "id": "istanbul_sultanahmet",
        "label": "Sultanahmet",
        "routeZone": "old_city",
        "planningMeaning": "Mosques, palaces, cisterns, museums, and high-density heritage."
      },
      {
        "id": "istanbul_beyoglu_galata",
        "label": "Beyoğlu and Galata",
        "routeZone": "new_city",
        "planningMeaning": "Views, nightlife, cafes, art, and hill walks."
      },
      {
        "id": "istanbul_bosphorus_asia",
        "label": "Bosphorus and Asian Side",
        "routeZone": "water",
        "planningMeaning": "Ferries, markets, waterfront neighborhoods, and lower-friction social flow."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Historical_peninsula_and_modern_skyline_of_Istanbul.jpg/800px-Historical_peninsula_and_modern_skyline_of_Istanbul.jpg",
      "source": "wikipedia",
      "pageTitle": "Istanbul",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "santorini",
    "destination": "Santorini",
    "aliases": [
      "Santorini, Greece"
    ],
    "country": "Greece",
    "currency": "EUR",
    "clusters": [
      {
        "id": "santorini_caldera_north",
        "label": "Oia and North Caldera",
        "routeZone": "north",
        "planningMeaning": "Sunset viewpoints, white villages, blue domes, and crowd-sensitive photo stops."
      },
      {
        "id": "santorini_fira_central",
        "label": "Fira and Central Island",
        "routeZone": "central",
        "planningMeaning": "Caldera walks, museums, wine, shopping, and flexible bases."
      },
      {
        "id": "santorini_south_beaches",
        "label": "South Beaches and Akrotiri",
        "routeZone": "south",
        "planningMeaning": "Archaeology, volcanic beaches, wineries, and slower day routes."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/2011_Dimos_Thiras.png/800px-2011_Dimos_Thiras.png",
      "source": "wikipedia",
      "pageTitle": "Santorini",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "singapore",
    "destination": "Singapore",
    "aliases": [
      "Singapore"
    ],
    "country": "Singapore",
    "currency": "SGD",
    "clusters": [
      {
        "id": "singapore_marina_bay",
        "label": "Marina Bay",
        "routeZone": "bay",
        "planningMeaning": "Skyline, gardens, museums, malls, and weather-safe showpiece anchors."
      },
      {
        "id": "singapore_heritage_districts",
        "label": "Heritage Districts",
        "routeZone": "central",
        "planningMeaning": "Chinatown, Little India, Kampong Glam, hawker food, and compact culture."
      },
      {
        "id": "singapore_sentosa_changi",
        "label": "Sentosa and Changi",
        "routeZone": "outer",
        "planningMeaning": "Beaches, airport gardens, family attractions, and transfer-friendly planning."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/800px-Flag_of_Singapore.svg.png",
      "source": "wikipedia",
      "pageTitle": "Singapore",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "reykjavik",
    "destination": "Reykjavik",
    "aliases": [
      "Reykjavik, Iceland",
      "Reykjavík"
    ],
    "country": "Iceland",
    "currency": "ISK",
    "clusters": [
      {
        "id": "reykjavik_city_center",
        "label": "Reykjavik Center",
        "routeZone": "central",
        "planningMeaning": "Churches, harbor, museums, food streets, and weather-safe city blocks."
      },
      {
        "id": "reykjavik_thermal_lagoon",
        "label": "Thermal Lagoons",
        "routeZone": "lagoon",
        "planningMeaning": "Blue Lagoon, Sky Lagoon, wellness buffers, and weather-resilient recovery."
      },
      {
        "id": "reykjavik_golden_circle",
        "label": "Golden Circle and South Coast",
        "routeZone": "outer",
        "planningMeaning": "Long-drive nature anchors, waterfalls, geysers, and seasonal route risk."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Reykjav%C3%ADk%2C_view_from_Hallgr%C3%ADmskirkja_%282%29.jpg/800px-Reykjav%C3%ADk%2C_view_from_Hallgr%C3%ADmskirkja_%282%29.jpg",
      "source": "wikipedia",
      "pageTitle": "Reykjavík",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "machu_picchu",
    "destination": "Machu Picchu",
    "aliases": [
      "Machu Picchu, Peru",
      "Cusco",
      "Cusco, Peru"
    ],
    "country": "Peru",
    "currency": "PEN",
    "clusters": [
      {
        "id": "machu_picchu_machu_picchu_sanctuary",
        "label": "Machu Picchu Sanctuary",
        "routeZone": "sanctuary",
        "planningMeaning": "Timed-entry ruins, mountain hikes, guides, and altitude-sensitive pacing."
      },
      {
        "id": "machu_picchu_aguas_calientes",
        "label": "Aguas Calientes",
        "routeZone": "base",
        "planningMeaning": "Arrival base, hot springs, early starts, train recovery, and logistics."
      },
      {
        "id": "machu_picchu_sacred_valley",
        "label": "Sacred Valley",
        "routeZone": "valley",
        "planningMeaning": "Ollantaytambo, Pisac, Maras, acclimatization, and longer transfer days."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Machu_Picchu%2C_2023_%28012%29.jpg/800px-Machu_Picchu%2C_2023_%28012%29.jpg",
      "source": "wikipedia",
      "pageTitle": "Machu Picchu",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "kyoto",
    "destination": "Kyoto",
    "aliases": [
      "Kyoto, Japan"
    ],
    "country": "Japan",
    "currency": "JPY",
    "clusters": [
      {
        "id": "kyoto_higashiyama_gion",
        "label": "Higashiyama and Gion",
        "routeZone": "east",
        "planningMeaning": "Temples, preserved lanes, geisha district, and high-crowd cultural icons."
      },
      {
        "id": "kyoto_arashiyama_west",
        "label": "Arashiyama and West Kyoto",
        "routeZone": "west",
        "planningMeaning": "Bamboo, river views, gardens, and slower outer flow."
      },
      {
        "id": "kyoto_north_central",
        "label": "North and Central Kyoto",
        "routeZone": "central",
        "planningMeaning": "Zen temples, markets, palace areas, and food recovery."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Kiyomizu.jpg/800px-Kiyomizu.jpg",
      "source": "wikipedia",
      "pageTitle": "Kyoto",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "venice",
    "destination": "Venice",
    "aliases": [
      "Venice, Italy"
    ],
    "country": "Italy",
    "currency": "EUR",
    "clusters": [
      {
        "id": "venice_san_marco_rialto",
        "label": "San Marco and Rialto",
        "routeZone": "core",
        "planningMeaning": "Basilica, palace, bridges, grand canal, and intense crowd management."
      },
      {
        "id": "venice_dorsoduro_cannaregio",
        "label": "Dorsoduro and Cannaregio",
        "routeZone": "local",
        "planningMeaning": "Art, quieter canals, cicchetti, and decompression routes."
      },
      {
        "id": "venice_lagoon_islands",
        "label": "Lagoon Islands",
        "routeZone": "lagoon",
        "planningMeaning": "Burano, Murano, boat days, color, glass, and wider breathing room."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Venezia_aerial_view.jpg/800px-Venezia_aerial_view.jpg",
      "source": "wikipedia",
      "pageTitle": "Venice",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "cairo",
    "destination": "Cairo",
    "aliases": [
      "Cairo, Egypt",
      "Egypt"
    ],
    "country": "Egypt",
    "currency": "EGP",
    "clusters": [
      {
        "id": "cairo_giza_plateau",
        "label": "Giza Plateau",
        "routeZone": "giza",
        "planningMeaning": "Pyramids, Sphinx, desert views, and exposed half-day anchors."
      },
      {
        "id": "cairo_central_cairo",
        "label": "Central Cairo",
        "routeZone": "central",
        "planningMeaning": "Museums, Nile, downtown logistics, and indoor recovery."
      },
      {
        "id": "cairo_islamic_coptic_cairo",
        "label": "Islamic and Coptic Cairo",
        "routeZone": "old_city",
        "planningMeaning": "Markets, mosques, citadel, churches, and layered heritage."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Cairo_Opera_House%2C_Al_Hurriyah_Park_and_the_Nile_river_%2814797782354%29.jpg/800px-Cairo_Opera_House%2C_Al_Hurriyah_Park_and_the_Nile_river_%2814797782354%29.jpg",
      "source": "wikipedia",
      "pageTitle": "Cairo",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "banff",
    "destination": "Banff National Park",
    "aliases": [
      "Banff",
      "Banff National Park, Canada"
    ],
    "country": "Canada",
    "currency": "CAD",
    "clusters": [
      {
        "id": "banff_lake_louise_moraine",
        "label": "Lake Louise and Moraine",
        "routeZone": "lakes",
        "planningMeaning": "Iconic lakes, shuttles, sunrise views, and crowd-controlled alpine anchors."
      },
      {
        "id": "banff_banff_town",
        "label": "Banff Town",
        "routeZone": "town",
        "planningMeaning": "Gondola, hot springs, restaurants, museums, and recovery logistics."
      },
      {
        "id": "banff_icefields_bow",
        "label": "Icefields and Bow Valley",
        "routeZone": "parkway",
        "planningMeaning": "Canyons, scenic drives, glaciers, lakes, and weather-sensitive road days."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Lake_Louise_17092005.jpg/800px-Lake_Louise_17092005.jpg",
      "source": "place_fallback",
      "pageTitle": "Banff National Park",
      "attribution": "Derived from first place image"
    },
    "replacementNote": null
  },
  {
    "destinationId": "zakouma_chad",
    "destination": "Zakouma National Park",
    "aliases": [
      "Chad",
      "Zakouma",
      "Zakouma National Park, Chad"
    ],
    "country": "Chad",
    "currency": "XAF",
    "clusters": [
      {
        "id": "zakouma_chad_zakouma_core",
        "label": "Zakouma Safari Core",
        "routeZone": "safari",
        "planningMeaning": "Wildlife drives, camp logistics, guides, and dry-season safari windows."
      },
      {
        "id": "zakouma_chad_salamat_wetlands",
        "label": "Bahr Salamat Wetlands",
        "routeZone": "wetlands",
        "planningMeaning": "Birdlife, seasonal water, conservation context, and remote nature."
      },
      {
        "id": "zakouma_chad_chad_culture_routes",
        "label": "Chad Culture Routes",
        "routeZone": "culture",
        "planningMeaning": "N'Djamena buffers, Ennedi, Lake Chad, and high-logistics expedition branches."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Girafe_du_parc_national_de_Zakouma.jpg/800px-Girafe_du_parc_national_de_Zakouma.jpg",
      "source": "place_fallback",
      "pageTitle": "Zakouma National Park",
      "attribution": "Derived from first place image"
    },
    "replacementNote": null
  },
  {
    "destinationId": "marrakech",
    "destination": "Marrakech",
    "aliases": [
      "Marrakech",
      "Marrakesh",
      "Morocco"
    ],
    "country": "Morocco",
    "currency": "MAD",
    "clusters": [
      {
        "id": "marrakech_medina_core",
        "label": "Medina Core",
        "routeZone": "medina",
        "planningMeaning": "Souks, squares, palaces, riads, and dense walking."
      },
      {
        "id": "marrakech_garden_new_city",
        "label": "Gardens and New City",
        "routeZone": "new_city",
        "planningMeaning": "Majorelle, Gueliz, spas, cafes, and recovery from medina intensity."
      },
      {
        "id": "marrakech_desert_edges",
        "label": "Desert and Atlas Edges",
        "routeZone": "outer",
        "planningMeaning": "Agafay, palm groves, day trips, and sunset experiences."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pavillon_Menarag%C3%A4rten.jpg/800px-Pavillon_Menarag%C3%A4rten.jpg",
      "source": "wikipedia",
      "pageTitle": "Marrakesh",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": "Replaces the duplicate Egypt request with a high-value North Africa city seed."
  },
  {
    "destinationId": "queenstown",
    "destination": "Queenstown",
    "aliases": [
      "Queenstown",
      "Queenstown, New Zealand"
    ],
    "country": "New Zealand",
    "currency": "NZD",
    "clusters": [
      {
        "id": "queenstown_queenstown_lakefront",
        "label": "Queenstown Lakefront",
        "routeZone": "town",
        "planningMeaning": "Lake Wakatipu, gardens, food, gondola, and low-friction town recovery."
      },
      {
        "id": "queenstown_adventure_rivers",
        "label": "Adventure Rivers",
        "routeZone": "adventure",
        "planningMeaning": "Jet boats, bungy, canyons, and high-adrenaline scheduling."
      },
      {
        "id": "queenstown_fiordland_glenorchy",
        "label": "Glenorchy and Fiordland",
        "routeZone": "outer",
        "planningMeaning": "Scenic drives, Milford Sound, long transfers, and weather-sensitive views."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/LakeWakatipuNov172024_02.jpg/800px-LakeWakatipuNov172024_02.jpg",
      "source": "place_fallback",
      "pageTitle": "Queenstown, New Zealand",
      "attribution": "Derived from first place image"
    },
    "replacementNote": "Replaces the duplicate Dubai request with a scenic adventure destination seed."
  },
  {
    "destinationId": "seoul",
    "destination": "Seoul",
    "aliases": [
      "Seoul",
      "Seoul, South Korea"
    ],
    "country": "South Korea",
    "currency": "KRW",
    "clusters": [
      {
        "id": "seoul_palace_hanok",
        "label": "Palace and Hanok Core",
        "routeZone": "north",
        "planningMeaning": "Royal palaces, hanok lanes, museums, and traditional culture."
      },
      {
        "id": "seoul_shopping_youth",
        "label": "Myeongdong, Hongdae, and DDP",
        "routeZone": "central",
        "planningMeaning": "Shopping, street food, youth districts, design, and nightlife."
      },
      {
        "id": "seoul_river_tower",
        "label": "River and Tower Views",
        "routeZone": "river",
        "planningMeaning": "Namsan, streams, parks, and lower-friction evening routes."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg/800px-%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg",
      "source": "wikipedia",
      "pageTitle": "Seoul",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": "Replaces the duplicate Tokyo request with a dense East Asia city seed."
  },
  {
    "destinationId": "oahu",
    "destination": "Oahu",
    "aliases": [
      "Hawaii",
      "Oahu",
      "Honolulu",
      "Oahu, Hawaii"
    ],
    "country": "USA",
    "currency": "USD",
    "clusters": [
      {
        "id": "oahu_honolulu_waikiki",
        "label": "Honolulu and Waikiki",
        "routeZone": "honolulu",
        "planningMeaning": "Beach, history, food, shopping, and low-friction city base."
      },
      {
        "id": "oahu_windward_east",
        "label": "Windward and East Oahu",
        "routeZone": "east",
        "planningMeaning": "Hikes, bays, beaches, ranches, and scenic drives."
      },
      {
        "id": "oahu_north_shore",
        "label": "North Shore",
        "routeZone": "north",
        "planningMeaning": "Surf, beaches, food trucks, turtle beaches, and day-trip pacing."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Oahu.jpg/800px-Oahu.jpg",
      "source": "wikipedia",
      "pageTitle": "Oahu",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "havana",
    "destination": "Havana",
    "aliases": [
      "Cuba",
      "Havana",
      "Havana, Cuba"
    ],
    "country": "Cuba",
    "currency": "CUP",
    "clusters": [
      {
        "id": "havana_old_havana",
        "label": "Old Havana",
        "routeZone": "old_city",
        "planningMeaning": "Plazas, colonial streets, museums, music, and compact walking."
      },
      {
        "id": "havana_vedado_malecon",
        "label": "Vedado and Malecón",
        "routeZone": "waterfront",
        "planningMeaning": "Seafront walks, nightlife, art, and social evenings."
      },
      {
        "id": "havana_daytrip_valleys",
        "label": "Valleys and Outer Art",
        "routeZone": "outer",
        "planningMeaning": "Viñales, Fusterlandia, beaches, and longer cultural branches."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/DJI_0197_crp_wiki.jpg/800px-DJI_0197_crp_wiki.jpg",
      "source": "wikipedia",
      "pageTitle": "Havana",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "madagascar",
    "destination": "Madagascar",
    "aliases": [
      "Madagascar",
      "Antananarivo",
      "Nosy Be"
    ],
    "country": "Madagascar",
    "currency": "MGA",
    "clusters": [
      {
        "id": "madagascar_tana_base",
        "label": "Antananarivo Base",
        "routeZone": "tana",
        "planningMeaning": "Arrival buffers, royal history, markets, and recovery before remote routes."
      },
      {
        "id": "madagascar_east_rainforest",
        "label": "Eastern Rainforest",
        "routeZone": "east",
        "planningMeaning": "Andasibe, lemurs, rainforest lodges, and wildlife walks."
      },
      {
        "id": "madagascar_west_south_islands",
        "label": "West, South, and Islands",
        "routeZone": "outer",
        "planningMeaning": "Baobabs, Tsingy, Isalo, Nosy Be, and long expedition routing."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Reconstructed_Rova_Antananarivo_Madagascar.jpg/800px-Reconstructed_Rova_Antananarivo_Madagascar.jpg",
      "source": "place_fallback",
      "pageTitle": "Madagascar",
      "attribution": "Derived from first place image"
    },
    "replacementNote": null
  },
  {
    "destinationId": "rotterdam",
    "destination": "Rotterdam",
    "aliases": [
      "Netherlands",
      "Rotterdam",
      "Rotterdam, Netherlands"
    ],
    "country": "Netherlands",
    "currency": "EUR",
    "clusters": [
      {
        "id": "rotterdam_modern_center",
        "label": "Modern Center",
        "routeZone": "center",
        "planningMeaning": "Architecture, markets, bridges, museums, and compact urban design."
      },
      {
        "id": "rotterdam_waterfront_docks",
        "label": "Waterfront and Docks",
        "routeZone": "waterfront",
        "planningMeaning": "Harbor views, river taxis, creative districts, and skyline walks."
      },
      {
        "id": "rotterdam_heritage_edges",
        "label": "Heritage Edges",
        "routeZone": "outer",
        "planningMeaning": "Delfshaven, Kinderdijk, and slower Dutch context beyond Amsterdam."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/A_view_of_Rotterdam%2C_taken_from_the_roof_of_the_Maassilo%2C_Rotterdam%2C_The_Netherlands.jpg/800px-A_view_of_Rotterdam%2C_taken_from_the_roof_of_the_Maassilo%2C_Rotterdam%2C_The_Netherlands.jpg",
      "source": "wikipedia",
      "pageTitle": "Rotterdam",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": "Represents the Netherlands request separately from Amsterdam."
  },
  {
    "destinationId": "lisbon",
    "destination": "Lisbon",
    "aliases": [
      "Lisbon",
      "Lisbon, Portugal"
    ],
    "country": "Portugal",
    "currency": "EUR",
    "clusters": [
      {
        "id": "lisbon_belem_west",
        "label": "Belém",
        "routeZone": "west",
        "planningMeaning": "Monuments, custard tarts, riverfront, museums, and low-gradient walks."
      },
      {
        "id": "lisbon_alfama_baixa",
        "label": "Alfama and Baixa",
        "routeZone": "central",
        "planningMeaning": "Hills, trams, viewpoints, food, and old-city walking."
      },
      {
        "id": "lisbon_creative_sintra",
        "label": "Creative Lisbon and Sintra",
        "routeZone": "outer",
        "planningMeaning": "LX Factory, markets, palaces, and day-trip branches."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Torre_Bel%C3%A9m_April_2009-4a.jpg/800px-Torre_Bel%C3%A9m_April_2009-4a.jpg",
      "source": "place_fallback",
      "pageTitle": "Lisbon",
      "attribution": "Derived from first place image"
    },
    "replacementNote": "Replaces the duplicate Amsterdam request with a strong Europe city-and-coast seed."
  },
  {
    "destinationId": "london",
    "destination": "London",
    "aliases": [
      "London",
      "London, UK",
      "London, England"
    ],
    "country": "United Kingdom",
    "currency": "GBP",
    "clusters": [
      {
        "id": "london_westminster_southbank",
        "label": "Westminster and South Bank",
        "routeZone": "central",
        "planningMeaning": "Royal/government icons, river walks, museums, markets, and theater flow."
      },
      {
        "id": "london_bloomsbury_city",
        "label": "Bloomsbury and City",
        "routeZone": "city",
        "planningMeaning": "Museums, finance-era heritage, towers, and indoor backups."
      },
      {
        "id": "london_west_end_parks",
        "label": "West End and Parks",
        "routeZone": "west",
        "planningMeaning": "Parks, shopping, Covent Garden, galleries, and social evenings."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/800px-London_Skyline_%28125508655%29.jpeg",
      "source": "wikipedia",
      "pageTitle": "London",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  },
  {
    "destinationId": "berlin",
    "destination": "Berlin",
    "aliases": [
      "Germany",
      "Berlin",
      "Berlin, Germany"
    ],
    "country": "Germany",
    "currency": "EUR",
    "clusters": [
      {
        "id": "berlin_mitte_memory",
        "label": "Mitte Memory Axis",
        "routeZone": "central",
        "planningMeaning": "Brandenburg Gate, Reichstag, museums, memorials, and walkable history."
      },
      {
        "id": "berlin_east_creative",
        "label": "East Berlin Creative Belt",
        "routeZone": "east",
        "planningMeaning": "Wall art, Kreuzberg, nightlife, markets, and alternative culture."
      },
      {
        "id": "berlin_west_parks_palaces",
        "label": "West Parks and Palaces",
        "routeZone": "west",
        "planningMeaning": "Charlottenburg, Tiergarten, Tempelhof, and lower-friction recovery."
      }
    ],
    "heroImage": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg/800px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg",
      "source": "wikipedia",
      "pageTitle": "Berlin",
      "attribution": "Wikipedia / Wikimedia Commons thumbnail"
    },
    "replacementNote": null
  }
];

const normalize = (value) => String(value || "").trim().toLowerCase();

export const getDestinationProfile = (destination) => {
  const normalized = normalize(destination);
  return destinationProfiles.find((profile) =>
    normalize(profile.destination) === normalized ||
    (profile.aliases || []).some((alias) => normalize(alias) === normalized)
  ) || null;
};

export const getDestinationImage = (destination) =>
  getDestinationProfile(destination)?.heroImage?.url || null;

export const getStaticMapImage = (coordinates) => {
  if (coordinates?.lat == null || coordinates?.lng == null) return null;
  return `https://staticmap.openstreetmap.de/staticmap.php?center=${coordinates.lat},${coordinates.lng}&zoom=14&size=800x600&markers=${coordinates.lat},${coordinates.lng},red-pushpin`;
};

export const getTripImage = (trip) =>
  trip?.image || getDestinationImage(trip?.destination || trip?.groupName);

export const getActivityImage = (activity, destination) =>
  activity?.image ||
  activity?.visualAssets?.image?.url ||
  activity?.mapImage ||
  getStaticMapImage(activity?.coordinates) ||
  getDestinationImage(destination);
